### PR TITLE
fix: powershell run command

### LINKED ISSUE #289: VHS doesn't work with Powershell
I can't run scripts in Powershell by command `Set Shell powershell`.

Example `example.tape` file: 
```
Output "demo.gif"

Set Shell powershell

Type "echo 'test'"
Sleep 500ms
Enter

Sleep 2s
```
This GIF is generated from this file with command `vhs example.tape`:

Made with VHS

**Setup**
OS: Windows 10
App: [Terminal](https://github.com/microsoft/terminal)
Shell: Powershell

### PR DESCRIPTION
**Pull request by gaskeo**
Fix #289 in [`shell.go` file](https://github.com/charmbracelet/vhs/blob/main/shell.go).

Remove `-Login` parameter because [official documentation hasn't it](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#syntax).

After removing `-Login` command `vhs` stacks on `Set Shell powershell` instruction. Fix this by changing `-Command` parameter.

**Example `.tape` file:** 
```
Output "demo.gif"

Set Shell powershell

Type "echo 'test'"
Sleep 500ms
Enter

Sleep 2s
```

**Fixed output:**

Made with VHS

### CODE REVIEW

File: shell.go [hunk 1]
```diff
@@ -40,12 +40,11 @@ var Shells = map[string]Shell{
 	powershell: {
 		Command: []string{
 			"powershell",
-			"-Login",
 			"-NoLogo",
 			"-NoExit",
 			"-NoProfile",
 			"-Command",
-			`Set-PSReadLineOption -HistorySaveStyle SaveNothing; Function prompt { Write-Host -ForegroundColor Blue -NoNewLine '>'; return ' ' }`,
+			`Set-PSReadLineOption -HistorySaveStyle SaveNothing; function prompt { Write-Host '>' -NoNewLine -ForegroundColor Blue; return ' ' }`,
```
Comment (caarlos0) [inline shell.go:47]: is this necessary too? why?

**Review by caarlos0 — APPROVED** [review]
hmm is this something new in powershell? My windows 11 VM had the `-Login` parameter when I was working on this... 


anyway, if its not needed, let's remove it 🤘

**Review by maaslalani — APPROVED** [review]

File: shell.go (hunk 1 above)
Comment (gaskeo) [reply shell.go:47]: After removing `-Login` command `vhs` stacks on `Set Shell powershell` instruction. I remove `-Command` parameter and all was fine. I checked how to rewrite default prompt in PS and write this `-Command` based on [this instruction](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.3)

Comment (caarlos0) [reply shell.go:47]: aahh cool, thanks for the info!
